version: "3.7"

services:
  api:
    container_name: BeTheHeroApi
    build:
      target: BeTheHero-API
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    command: npm start
    volumes:
      - ./src:usr/app
    environment:
      SECRET:
